# Generated by Django 5.1.6 on 2025-02-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=50)),
                ('enter_timestamp', models.DateTimeField()),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detectionrecord',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
