# Generated by Django 5.1.6 on 2025-02-18 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_personsession_alter_detectionrecord_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsession',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personsession',
            name='appearance_feature',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectionrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personsession',
            name='enter_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
