# Generated by Django 5.1.6 on 2025-02-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionRecord',
        ),
    ]
