# Generated by Django 5.1.6 on 2025-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='last_predicted_category',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationrequest',
            name='last_predicted_wait_mins',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
