# Generated by Django 5.1.6 on 2025-04-05 17:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0002_notificationrequest_last_predicted_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_preference', models.CharField(max_length=10)),
                ('rating_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_notification', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
