# Generated by Django 5.1.6 on 2025-04-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
