# Generated by Django 5.1.6 on 2025-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0004_notificationrequest_confirmation_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating_experience',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating_notification',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_ease_of_use',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_notification_usefulness',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_overall_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_recommendation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
