# Generated by Django 5.1.6 on 2025-04-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0005_remove_feedback_rating_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
