# Generated by Django 5.1.6 on 2025-03-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(help_text='The date/time the appointment is scheduled to begin.')),
                ('duration_minutes', models.PositiveIntegerField(default=15, help_text='Expected length of the appointment in minutes.')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('patient_name', models.CharField(blank=True, help_text="Patient's name if booked.", max_length=100, null=True)),
                ('patient_email', models.EmailField(blank=True, help_text="Patient's email if booked (for notifications).", max_length=254, null=True)),
                ('predicted_delay', models.IntegerField(blank=True, help_text="Delay in seconds above the scheduled slot's duration.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
