# Generated by Django 5.1.6 on 2025-03-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='predicted_delay',
            field=models.IntegerField(blank=True, help_text='Auto-calculated delay in seconds above the slot duration.', null=True),
        ),
    ]
