# Generated by Django 5.1.6 on 2025-03-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_predicted_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='The time the appointment was completed.', null=True),
        ),
    ]
